kind: pipeline
name: default

steps:
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      username: app-mochi-matchを監視しているはじめ
      avatar_url: https://cdn.discordapp.com/attachments/719600379725217903/720465090289336380/20200601_161405.jpg
      webhook_id:
        from_secret: DISCORD_WEBHOCK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOCK_TOKEN
      message: >
        {{#success build.status}}
         #{{build.number}} 成功、やるやん
        {{else}}
         #{{build.number}} fuck off.
        {{/success}}
trigger:
  event:
    - push