FORMAT: 1A

# MochiMochi API

# Data Structures

## Room (object)
+ room_id: 1 (number) - ルーム識別番号
+ owner_id: 1 (number) - ホストユーザ識別番号
+ icon: 1 (number) - ホストアイコン識別番号
+ name: ﾓቻﾓቻ (string) - ホストユーザ名
+ hard: 1 (number) - ゲームハード識別番号
+ title: MOCHIMOCHI (string) - ゲームタイトル名
+ capacity: 4 (number) - 制限人数
+ text: もちもちしたい人集まれ～＞＜ (string) - 募集テキスト
+ created: 4月5日 16時50分 (string) - ルーム作成日時
+ start: 14時30分 (string) - ルーム開始時間

# Group Room
## ルームリスト全取得 [GET /room/list]
現在立っているルームを全件取得

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (Room)
        + (Room)

## ルームリスト取得（ページ） [GET /room/list/{page}]
現在立っているルームを指定されたページ数で取得、最大6件

+ Parameters
    + page: 1 (number) - ページ数

+ Response 200 (application/json)
    + Attributes (array, fixed-type)
        + (Room)
        + (Room)

# Group Game
## お気に入りゲーム取得 [GET /favorite-game/{id}]
ユーザが登録しているお気に入りゲームの取得

+ Parameters
    + id: 1 (number) - ユーザ識別番号

+ Response 200 (application/json)
    + Body
    ```
    [
        {
            "favorite": [
                "モンスト",
                "パズドラ",
                "グラブル",
                "ダー糞ウル（糞）"
            ]
        }
    ]
    ```

## 人気ゲーム取得 [GET /popular-game]
今一番ホットなゲーム

+ Response 200 (application/json)
    + Body
    ```
    [
        {
            "popular": [
                "ダー糞ウル（糞）",
                "パズドラ",
                "モンスト",
                "グラブル"
            ]
        }
    ]
    ```
        